export const OfferTypes = {
  SET_DIALOG_URL: 'SET_DIALOG_URL',
  SET_DIALOG_OFFER: 'SET_DIALOG_OFFER',

  POST_URL_START: 'POST_URL_START',
  POST_URL_SUCCESS: 'POST_URL_SUCCESS',
  POST_URL_FAIL: 'POST_URL_FAIL',

  POST_OFFER_START: 'POST_OFFER_START',
  POST_OFFER_SUCCESS: 'POST_OFFER_SUCCESS',
  POST_OFFER_FAIL: 'POST_OFFER_FAIL',
}