export const UsersTypes = {
  FETCH_USERS_START: 'FETCH_USERS_START',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAIL: 'FETCH_USERS_FAIL',

  SET_BALANCE_START: 'SET_BALANCE_START',
  SET_BALANCE_SUCCESS: 'SET_BALANCE_SUCCESS',
  SET_BALANCE_FAIL: 'SET_BALANCE_FAIL',

}