export const UsersTypes = {
  FETCH_USERS_START: 'FETCH_USERS_START',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAIL: 'FETCH_USERS_FAIL',

  EDIT_BALANCE_START: 'EDIT_BALANCE_START',
  EDIT_BALANCE_SUCCESS: 'EDIT_BALANCE_SUCCESS',
  EDIT_BALANCE_FAIL: 'EDIT_BALANCE_FAIL',

  MODIFY_BALANCE_START: 'MODIFY_BALANCE_START',
  MODIFY_BALANCE_SUCCESS: 'MODIFY_BALANCE_SUCCESS',
  MODIFY_BALANCE_FAIL: 'MODIFY_BALANCE_FAIL',
}