export const OffersTypes = {
  FETCH_OFFERS_START: 'FETCH_OFFERS_START',
  FETCH_OFFERS_SUCCESS: 'FETCH_OFFERS_SUCCESS',
  FETCH_OFFERS_FAIL: 'FETCH_OFFERS_FAIL',

  CLEAR_ERROR_OFFERS_START: 'CLEAR_ERROR_OFFERS_START',
  CLEAR_ERROR_OFFERS_SUCCESS: 'CLEAR_ERROR_OFFERS_SUCCESS',
  CLEAR_ERROR_OFFERS_FAIL: 'CLEAR_ERROR_OFFERS_FAIL',
}