export const RarityFilterTypes = {
  RARITY_FILTER_START: 'RARITY_FILTER_START',
  RARITY_FILTER_FINISH: 'RARITY_FILTER_FINISH',
  RESET_RARITY_FILTER: 'RESET_RARITY_FILTER',

  SET_RARITY_CONTAINER: 'SET_RARITY_CONTAINER'
}