export const HeroesTypes = {
  FETCH_HEROES_START: 'FETCH_HEROES_START',
  FETCH_HEROES_SUCCESS: 'FETCH_HEROES_SUCCESS',
  FETCH_HEROES_FAIL: 'FETCH_HEROES_FAIL',

  SET_HEROES_RENDERED: 'SET_HEROES_RENDERED',
  SET_HERO_CONTAINER: 'SET_HERO_CONTAINER',

  FILTER_HEROES_START: 'FILTER_HEROES_START',
  FILTER_HEROES_FINISH: 'FILTER_HEROES_FINISH',

  RESET_HERO_FILTER: 'RESET_HERO_FILTER'
}