export const ClientStatesTypes = {
  TOGGLE_BLACK_SCREEN: 'TOGGLE_BLACK_SCREEN',
  FETCH_OFFER_STATUS_START: 'FETCH_OFFER_STATUS_START',
  FETCH_OFFER_STATUS_SUCCESS: 'FETCH_OFFER_STATUS_SUCCESS',
  FETCH_OFFER_STATUS_FAILURE: 'FETCH_OFFER_STATUS_FAILURE',
}