export const AdminTypes = {
  LOG_IN_START: 'LOG_IN_START',
  LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
  LOG_IN_FAIL: 'LOG_IN_FAIL',

  BACKGROUND_LOG_IN_START: 'BACKGROUND_LOG_IN_START',
  BACKGROUND_LOG_IN_SUCCESS: 'BACKGROUND_LOG_IN_SUCCESS',
  BACKGROUND_LOG_IN_FAIL: 'BACKGROUND_LOG_IN_FAIL',

  UPDATE_PASSWORD_START: 'UPDATE_PASSWORD_START',
  UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAIL: 'UPDATE_PASSWORD_FAIL',
}