export const OverlayTypes = {
  OVERLAY_PUSH: 'OVERLAY_PUSH',
  OVERLAY_POP_START: 'OVERLAY_POP_START',
  OVERLAY_POP_FINISH: 'OVERLAY_POP_FINISH',

  UPDATE_LAST_STACK_START: 'UPDATE_LAST_STACK_START',
  UPDATE_LAST_STACK_FINISH: 'UPDATE_LAST_STACK_FINISH',
}