export const SiteSettingsTypes = {
  FETCH_SITE_SETTINGS_START: 'FETCH_SITE_SETTINGS_START',
  FETCH_SITE_SETTINGS_SUCCESS: 'FETCH_SITE_SETTINGS_SUCCESS',
  FETCH_SITE_SETTINGS_FAIL: 'FETCH_SITE_SETTINGS_FAIL',

  FETCH_CURRENCY_RATE_START: 'FETCH_CURRENCY_RATE_START',
  FETCH_CURRENCY_RATE_SUCCESS: 'FETCH_CURRENCY_RATE_SUCCESS',
  FETCH_CURRENCY_RATE_FAIL: 'FETCH_CURRENCY_RATE_FAIL',
}