export const TempItemTypes = {
  SET_BOT_TEMP_ITEM: 'SET_BOT_TEMP_ITEM',
  UNSET_BOT_TEMP_ITEM: 'UNSET_BOT_TEMP_ITEM',
  SET_USER_TEMP_ITEM: 'SET_USER_TEMP_ITEM',
  UNSET_USER_TEMP_ITEM: 'UNSET_USER_TEMP_ITEM',
}