export const ItemTypes = {
  FETCH_ITEM_START: 'FETCH_ITEM_START',
  FETCH_ITEM_SUCCESS: 'FETCH_ITEM_SUCCESS',
  FETCH_ITEM_FAIL: 'FETCH_ITEM_FAIL',

  POST_ITEM_START: 'POST_ITEM_START',
  POST_ITEM_SUCCESS: 'POST_ITEM_SUCCESS',
  POST_ITEM_FAIL: 'POST_ITEM_FAIL',

  FETCH_ITEMS_START: 'FETCH_ITEMS_START',
  FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
  FETCH_ITEMS_FAIL: 'FETCH_ITEMS_FAIL',
}