export const InventoryActionTypes = {
  FETCH_BOT_INVENTORY_START: 'FETCH_BOT_INVENTORY_START',
  FETCH_USER_INVENTORY_START: 'FETCH_USER_INVENTORY_START',
  FETCH_BOT_INVENTORY_SUCCESS: 'FETCH_BOT_INVENTORY_SUCCESS',
  FETCH_USER_INVENTORY_SUCCESS: 'FETCH_USER_INVENTORY_SUCCESS',
  FETCH_BOT_INVENTORY_FAILURE: 'FETCH_BOT_INVENTORY_FAILURE',
  FETCH_USER_INVENTORY_FAILURE: 'FETCH_USER_INVENTORY_FAILURE',

}