export const InventoryActionTypes = {
  FETCH_BOT_INVENTORY_START: 'FETCH_BOT_INVENTORY_START',
  FETCH_USER_INVENTORY_START: 'FETCH_USER_INVENTORY_START',
  FETCH_BOT_INVENTORY_SUCCESS: 'FETCH_BOT_INVENTORY_SUCCESS',
  FETCH_USER_INVENTORY_SUCCESS: 'FETCH_USER_INVENTORY_SUCCESS',
  FETCH_BOT_INVENTORY_FAILURE: 'FETCH_BOT_INVENTORY_FAILURE',
  FETCH_USER_INVENTORY_FAILURE: 'FETCH_USER_INVENTORY_FAILURE',

  RENDERED_INVENTORY_UPDATE_INTERVAL: 20,

  UPDATE_BOT_RENDERED_INVENTORY: 'UPDATE_BOT_RENDERED_INVENTORY',
  UPDATE_USER_RENDERED_INVENTORY: 'UPDATE_USER_RENDERED_INVENTORY',
}