export const InventoryActionTypes = {
  FETCH_INVENTORY_START: 'FETCH_BOT_INVENTORY_START',
  FETCH_INVENTORY_SUCCESS: 'FETCH_BOT_INVENTORY_SUCCESS',
  FETCH_INVENTORY_FAILURE: 'FETCH_BOT_INVENTORY_FAILURE',

  REFRESH_INVENTORY_START: 'REFRESH_BOT_INVENTORY_START',

  RENDERED_INVENTORY_UPDATE_INTERVAL: 20,

  UPDATE_RENDERED_INVENTORY_START: 'UPDATE_BOT_RENDERED_INVENTORY_START',
  UPDATE_RENDERED_INVENTORY: 'UPDATE_BOT_RENDERED_INVENTORY',

  SET_RENDERING_INVENTORY: 'SET_RENDERING_INVENTORY',
  SET_RENDERING_INVENTORY_START: 'SET_RENDERING_INVENTORY_START',

  SET_BALANCE_ITEM_START: 'SET_BALANCE_ITEM_START',
  SET_BALANCE_ITEM_FINISH: 'SET_BALANCE_ITEM_FINISH'
}