export const InventoryActionTypes = {
  FETCH_INVENTORY_START: 'FETCH_BOT_INVENTORY_START',
  FETCH_INVENTORY_SUCCESS: 'FETCH_BOT_INVENTORY_SUCCESS',
  FETCH_INVENTORY_FAILURE: 'FETCH_BOT_INVENTORY_FAILURE',

  FETCH_ALL_INVENTORY: 'FETCH_ALL_INVENTORY'
}