export const SiteConfigsTypes = {
  FETCH_SITE_CONFIGS_START: 'FETCH_SITE_CONFIGS_START',
  FETCH_SITE_CONFIGS_SUCCESS: 'FETCH_SITE_CONFIGS_SUCCESS',
  FETCH_SITE_CONFIGS_FAIL: 'FETCH_SITE_CONFIGS_FAIL',

  PUT_SITE_CONFIG_START: 'PUT_SITE_CONFIG_START',
  PUT_SITE_CONFIG_SUCCESS: 'PUT_SITE_CONFIG_SUCCESS',
  PUT_SITE_CONFIG_FAIL: 'PUT_SITE_CONFIG_FAIL',
}