export const CurrencyTypes = {
  SET_CURRENCY: 'SET_CURRENCY',

  FETCH_CURRENCY_RATE_START: 'FETCH_CURRENCY_RATE_START',
  FETCH_CURRENCY_RATE_SUCCESS: 'FETCH_CURRENCY_RATE_SUCCESS',
  FETCH_CURRENCY_RATE_FAILURE: 'FETCH_CURRENCY_RATE_FAILURE'
}