export const SearchingTypes = {

  SET_QUERY_ITEMS_START: 'SET_QUERY_ITEMS_START',

  SET_QUERY_ITEMS: 'SET_BOT_QUERY_ITEMS',

  REFRESH_QUERY: 'REFRESH_BOT_QUERY',

  HERO_SEARCHING_START: 'HERO_SEARCHING_START',
}