export const SearchingTypes = {
  SET_BOT_SEARCHING_QUERY: 'SET_BOT_SEARCHING_QUERY',
  SET_USER_SEARCHING_QUERY: 'SET_USER_SEARCHING_QUERY',

  SET_BOT_QUERY_ITEMS: 'SET_BOT_QUERY_ITEMS',
  SET_USER_QUERY_ITEMS: 'SET_USER_QUERY_ITEMS',
}