export const UserTypes = {
  LOG_IN_START: 'LOG_IN_START',
  LOG_IN_SUCCESSFUL: 'LOG_IN_SUCCESSFUL',
  LOG_IN_FAIL: 'LOG_IN_FAIL',

  FETCH_OFFERS_START: 'FETCH_OFFERS_START',
  FETCH_OFFERS_SUCCESSFUL: 'FETCH_OFFERS_SUCCESSFUL',
  FETCH_OFFERS_FAILED: 'FETCH_OFFERS_FAILED',

  LOG_OUT: 'LOG_OUT',

  EDIT_USER_INFO: 'EDIT_USER_INFO',
  EDIT_USER_INFO_FINISH: 'EDIT_USER_INFO_FINISH',
}