export const UserTypes = {
  LOG_IN_START: 'LOG_IN_START',
  LOG_IN_SUCCESSFUL: 'LOG_IN_SUCCESSFUL',
  LOG_IN_FAIL: 'LOG_IN_FAIL',

  LOG_OUT: 'LOG_OUT',

  EDIT_USER_INFO: 'EDIT_USER_INFO',
  EDIT_USER_INFO_FINISH: 'EDIT_USER_INFO_FINISH',
}